version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wasted
      POSTGRES_DB: MusicLibrary
    ports:
      - "5431:5432"
    volumes:
      - music_library_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: wasted
      DB_NAME: MusicLibrary
      DB_PORT: 5432
      SERVER_PORT: :63342
    ports:
      - "63342:63342"
    depends_on:
      - db

volumes:
  music_library_data:
