version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wasted
      POSTGRES_DB: MusicLibrary
    ports:
      - "5431:5432"
    volumes:
      - music_library_data:/var/lib/postgresql/data

volumes:
  music_library_data:
